### ISSUE TITLE
kuja apa

### ISSUE THREAD

**Issue by gavinmasese** [vincentkims49/vincentkims49#1]
@vincentkims49

**Comment by vincentkims49** [comment]
Sema

**Comment by gavinmasese** [comment]
rename hii ikue vincentkims49

**Comment by gavinmasese** [comment]
na uchange readme yako ikue na jina ingine

**Comment by vincentkims49** [comment]
Issue ama?

**Comment by gavinmasese** [comment]
wacha nicreate pr kwa readme yako saizi sijui utamerge au

**Comment by gavinmasese** [comment]
ziiii repo mzima
enda kwa repository settings uchange jina

**Comment by vincentkims49** [comment]
> rename hii ikue vincentkims49



> ziiii repo mzima enda kwa repository settings uchange jina

Inajiita vincentkims49.1

**Comment by vincentkims49** [comment]
> wacha nicreate pr kwa readme yako saizi sijui utamerge au

Poa

**Comment by gavinmasese** [comment]
change repo yako yenye inajiita vincentkims49 ikie jina yoyote ingine
na hii yenye inajiita vincentkims49.1 ikue vincentkims49

**Comment by gavinmasese** [comment]
nakucreatia pr tho

**Comment by vincentkims49** [comment]
Changed

**Comment by gavinmasese** [comment]
wazi si hio readme iko sawa?

**Comment by gavinmasese** [comment]
change links za ig linkedin na gmail
sikua sure

**Comment by vincentkims49** [comment]
Ungecopy Kwa my last readme

**Comment by gavinmasese** [comment]
naeza tengeneza tu pr later on ukuje umerge isikupee stress

**Comment by vincentkims49** [comment]
Then
